import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Product, ProductImage, Specification } from "./types";

/**
 * CATÁLOGO REAL — lista de vendas da própria loja
 * =================================================
 *
 * Estes produtos vêm da lista de vendas que a Dom Guima usa no WhatsApp
 * (arquivo "VENDAS NOVO.txt", recebido do lojista em 20/08/2026). Preço,
 * marca, especificação e voltagem são REAIS — a taxa do cartão inclusive,
 * que aqui é exibida como o lojista informa (com taxa), não calculada como
 * "sem juros".
 *
 * O que NÃO temos ainda: foto do produto em si (por isso `dataSource:
 * "loja-verified"`, não "shopee-verified") e dado de venda/avaliação — por
 * isso nenhum item aqui carrega desconto, "mais vendido" ou nota. Adicionar
 * isso depois é só preencher `oldPrice`, `isBestSeller` ou `rating` no
 * produto correspondente.
 *
 * Peso e dimensões são ESTIMATIVAS logísticas por categoria (para o cálculo
 * de frete funcionar), não especificação de produto — ajuste quando tiver a
 * medida real da caixa.
 */

const LOJA_VERIFIED_AT = "2026-08-20";

const PLACEHOLDER_IMG = (key: string) => `/placeholder/${key}.svg`;

/**
 * Raiz de /public, calculada a partir deste arquivo — para checar em disco
 * se já existe foto real baixada, sem depender do diretório de onde o
 * processo Node foi iniciado.
 */
const PUBLIC_DIR = join(process.cwd(), "public");

/**
 * Detecta foto REAL do produto em /public/produtos/<slug>/1.jpg, 2.jpg... —
 * pesquisada e baixada à parte (ver processo de importação de fotos).
 * Sem foto real ainda, cai na ilustração — nunca mistura as duas nem finge
 * que a ilustração é uma foto.
 */
function resolveImages(slug: string, name: string, fallbackKey: string): ProductImage[] {
  const dir = join(PUBLIC_DIR, "produtos", slug);
  const real: ProductImage[] = [];

  // `cover.webp` e a capa padronizada da vitrine. As fotos originais continuam
  // depois dela para preservar detalhes, informacoes e cenas de uso na galeria.
  const cover = join(dir, "cover.webp");
  if (existsSync(cover)) {
    real.push({ src: `/produtos/${slug}/cover.webp`, alt: `${name} — foto principal` });
  }
  // O catalogo de fotos enviado pelo dono tem prioridade na galeria. Arquivos
  // numerados preservam variacoes de cor sem apagar as fotos tecnicas atuais.
  for (let i = 1; i <= 6; i++) {
    const file = join(dir, `owner-${i}.webp`);
    if (!existsSync(file)) break;
    real.push({
      src: `/produtos/${slug}/owner-${i}.webp`,
      alt: `${name} — foto do catalogo Dom Guima ${i}`,
    });
  }
  for (let i = 1; i <= 6; i++) {
    const file = join(dir, `${i}.jpg`);
    if (!existsSync(file)) break;
    real.push({ src: `/produtos/${slug}/${i}.jpg`, alt: `${name} — foto ${i}` });
  }
  if (real.length > 0) return real;
  return [{ src: PLACEHOLDER_IMG(fallbackKey), alt: `${name} — imagem ilustrativa` }];
}

interface LojaDraft {
  name: string;
  brand?: string;
  model?: string;
  categoryId: string;
  /** Centavos — preço à vista informado pelo lojista (Pix ou dinheiro). */
  price: number;
  /** [parcelas, valor da parcela em centavos] — com taxa do cartão, real. */
  card: [number, number];
  img: string;
  bullets: string[];
  voltage?: string[];
  color?: string[];
  /** Gramas — estimativa logística. */
  weight: number;
  /** cm — [comprimento, largura, altura], estimativa logística. */
  dims: [number, number, number];
  /** Observação pontual do lojista (frete grátis, comparação de preço etc.). */
  note?: string;
  /** Linha própria/exclusiva da Dom Guima. */
  exclusive?: boolean;
}

const drafts: LojaDraft[] = [
  // ─── ACESSÓRIOS (DG SHOP) ───────────────────────────────────────────────
  {
    name: "Suporte Duplo para Controle PS5",
    exclusive: true,
    categoryId: "eletronicos",
    price: 5990,
    card: [12, 570],
    img: "suporte",
    bullets: [
      "Suporta até 2 controles PS5 com organização e praticidade",
      "Acesso para cabo de carregamento sem retirar os controles do suporte",
      "Design moderno que valoriza o setup gamer",
      "Material resistente com bom acabamento e durabilidade",
    ],
    color: ["Preto", "Branco"],
    weight: 300,
    dims: [20, 12, 15],
    note: "Entrega grátis em Uberlândia",
  },
  {
    name: "Suporte Veicular para Starlink Mini com Ventosa Dupla",
    exclusive: true,
    categoryId: "eletronicos",
    price: 11990,
    card: [12, 1420],
    img: "suporte",
    bullets: [
      "Dupla ventosa com trava para fixação ultra segura",
      "Tiras de EVA que protegem o painel contra riscos e marcas",
      "Instalação rápida e remoção fácil sem danificar a superfície",
      "Design resistente desenvolvido para uso veicular",
    ],
    color: ["Preto", "Branco", "Cinza"],
    weight: 350,
    dims: [18, 15, 10],
  },
  {
    name: "Película Protetora para Starlink Mini",
    exclusive: true,
    categoryId: "eletronicos",
    price: 3990,
    card: [12, 377],
    img: "suporte",
    bullets: [
      "Ajuda a proteger contra riscos, arranhões e desgaste do uso diário",
      "Encaixe preciso desenvolvido exclusivamente para Starlink Mini",
      "Acabamento premium que preserva o visual moderno do equipamento",
      "Instalação rápida e prática, sem necessidade de adaptações",
    ],
    color: ["Preto fosco"],
    weight: 80,
    dims: [15, 15, 2],
  },
  {
    name: "Kit Starlink Mini — Suporte Veicular + Película Protetora",
    exclusive: true,
    categoryId: "eletronicos",
    price: 14990,
    card: [12, 1770],
    img: "suporte",
    bullets: [
      "Dupla ventosa com trava para fixação ultra segura no veículo",
      "Película protetora premium contra riscos, arranhões e desgaste",
      "Tiras de EVA que protegem o painel contra marcas e danos",
      "Instalação rápida e remoção fácil sem danificar superfícies",
    ],
    color: ["Preto", "Branco", "Cinza"],
    weight: 420,
    dims: [20, 15, 10],
  },
  {
    name: "Suporte Veicular para Starlink Mini + Carregador Veicular",
    exclusive: true,
    categoryId: "eletronicos",
    price: 23990,
    card: [12, 2260],
    img: "suporte",
    bullets: [
      "Dupla ventosa com trava para fixação ultra segura no veículo",
      "Acompanha carregador veicular para utilização em movimento",
      "Tiras de EVA que protegem o painel contra riscos e marcas",
      "Design resistente e posicionamento discreto para uso diário",
    ],
    color: ["Preto", "Branco", "Cinza"],
    weight: 450,
    dims: [20, 15, 10],
  },
  {
    name: "Suporte para Celular Tênis, Beach Tennis e Padel — DG Shop",
    exclusive: true,
    categoryId: "celulares",
    price: 5990,
    card: [12, 565],
    img: "suporte",
    bullets: [
      "Ajuste de ângulo para gravar e acompanhar as partidas na posição ideal",
      "Fixação segura na rede para mais estabilidade durante o uso",
      "Compatibilidade universal com a maioria dos modelos de celular",
      "Design portátil e leve, fácil de transportar para qualquer quadra",
    ],
    weight: 250,
    dims: [18, 10, 8],
  },
  {
    name: "Organizador de Cabos para Starlink Mini — DG Shop",
    exclusive: true,
    categoryId: "eletronicos",
    price: 5990,
    card: [12, 565],
    img: "cabo",
    bullets: [
      "Elimina a bagunça dos cabos e deixa o setup mais organizado",
      "Design compacto e portátil que ocupa pouco espaço",
      "Material resistente para maior durabilidade no uso diário",
      "Instalação rápida e prática, sem necessidade de ferramentas",
    ],
    color: ["Preto", "Branco", "Cinza"],
    weight: 150,
    dims: [15, 10, 5],
  },

  // ─── CLIMATIZAÇÃO ───────────────────────────────────────────────────────
  {
    name: "Ar Condicionado Philco Inverter 9000 BTUs Frio PAC9FT",
    brand: "Philco",
    categoryId: "climatizacao",
    price: 189990,
    card: [12, 17895],
    img: "arcondicionado",
    bullets: [
      "Tecnologia Inverter para mais economia e temperatura mais estável",
      "Potência de 810W e classificação energética A",
      "Serpentina de cobre e gás R32",
      "Modos automático, resfriar, ventilar, desumidificar e turbo",
      "Funções dormir, timer, silêncio e oscilar",
      "Filtro antibactéria lavável e revestimento anticorrosivo",
    ],
    voltage: ["220V"],
    weight: 27000,
    dims: [90, 30, 25],
  },
  {
    name: "Ar-Condicionado Consul Triple Inverter 9.000 BTUs CBK09DB Frio",
    brand: "Consul",
    categoryId: "climatizacao",
    price: 209990,
    card: [12, 19775],
    img: "arcondicionado",
    bullets: [
      "Tecnologia Triple Inverter para mais economia de energia e refrigeração rápida",
      "Exclusivo sistema bivolt que facilita a instalação em diferentes ambientes",
      "Serpentina em cobre com maior durabilidade e resistência à corrosão",
      "Função Sono Bom que ajusta a temperatura para mais conforto durante a noite",
      "Funções refrigerar, desumidificar e ventilar",
    ],
    voltage: ["Bivolt (unidade interna)"],
    weight: 27000,
    dims: [90, 30, 25],
  },
  {
    name: "Ar Condicionado Philco Inverter 12000 BTUs Frio PAC12FC",
    brand: "Philco",
    categoryId: "climatizacao",
    price: 209990,
    card: [12, 19775],
    img: "arcondicionado",
    bullets: [
      "Tecnologia Eco Inverter para mais economia e temperatura mais estável",
      "Potência de 1080W e classificação energética A",
      "Serpentina de cobre e gás R32",
      "Modos automático, resfriar, ventilar, desumidificar e turbo",
      "Filtro antibactéria lavável e revestimento anticorrosivo",
    ],
    voltage: ["220V"],
    weight: 30000,
    dims: [95, 32, 27],
  },
  {
    name: "Ar-Condicionado Elgin Inverter 12.000 BTUs HIFE12C2CA Frio",
    brand: "Elgin",
    categoryId: "climatizacao",
    price: 229990,
    card: [12, 21660],
    img: "arcondicionado",
    bullets: [
      "Wi-Fi integrado com controle pelo celular e comandos de voz",
      "Tecnologia Inverter para mais economia de energia e funcionamento silencioso",
      "Função i Feel que ajusta automaticamente a temperatura conforme sua localização",
      "Serpentina de cobre e filtro antibactéria",
      "Função autolimpeza que ajuda a evitar mofo, bactérias e maus odores",
    ],
    voltage: ["220V"],
    weight: 30000,
    dims: [95, 32, 27],
    note: "Mais de R$ 2.700 em lojas físicas",
  },
  {
    name: "Ar-Condicionado Philco Inverter 12.000 BTUs PAC12QC Quente/Frio",
    brand: "Philco",
    categoryId: "climatizacao",
    price: 229990,
    card: [12, 21660],
    img: "arcondicionado",
    bullets: [
      "Ciclo quente e frio para conforto durante todo o ano",
      "Tecnologia Eco Inverter que reduz o consumo de energia e mantém a temperatura estável",
      "Filtro lavável com proteção contra fungos e bactérias",
      "Funções turbo, dormir e desumidificar",
      "Garantia de até 10 anos no compressor",
    ],
    voltage: ["220V"],
    weight: 30000,
    dims: [95, 32, 27],
    note: "Mais de R$ 2.700 em lojas físicas",
  },
  {
    name: "Ar-Condicionado Samsung Inverter 12.000 BTUs AR12DYFAAWKXAZ Frio",
    brand: "Samsung",
    categoryId: "climatizacao",
    price: 239990,
    card: [12, 22601],
    img: "arcondicionado",
    bullets: [
      "Tecnologia WindFree que climatiza o ambiente sem jatos de ar diretos",
      "Wi-Fi integrado com controle remoto pelo app SmartThings",
      "Digital Inverter para mais economia de energia e funcionamento silencioso",
      "Filtro antibactéria e função Auto Clean",
      "Garantia de até 10 anos no compressor",
    ],
    voltage: ["220V"],
    weight: 30000,
    dims: [95, 32, 27],
    note: "Mais de R$ 2.700 em lojas físicas",
  },
  {
    name: "Climatizador de Ar Britânia BCL05A",
    brand: "Britânia",
    categoryId: "climatizacao",
    price: 41990,
    card: [12, 3955],
    img: "arcondicionado",
    bullets: [
      "4 em 1: climatiza, ventila, umidifica e filtra o ar",
      "Reservatório de 5L com autonomia de até 26 horas",
      "3 velocidades para ajustar o conforto conforme sua necessidade",
      "Rodas de transporte para mover o aparelho com facilidade",
    ],
    voltage: ["220V"],
    weight: 11000,
    dims: [38, 38, 88],
  },
  {
    name: "Climatizador de Ar Philco PCL05A",
    brand: "Philco",
    categoryId: "climatizacao",
    price: 41990,
    card: [12, 3955],
    img: "arcondicionado",
    bullets: [
      "4 em 1: climatiza, ventila, umidifica e filtra o ar",
      "Reservatório de 5L com autonomia de até 26 horas",
      "Controle remoto para mais praticidade no dia a dia",
      "3 velocidades e funcionamento silencioso",
    ],
    voltage: ["220V"],
    weight: 11000,
    dims: [38, 38, 88],
  },
  {
    name: "Aquecedor Britânia AB1100N",
    brand: "Britânia",
    categoryId: "climatizacao",
    price: 12990,
    card: [12, 1224],
    img: "arcondicionado",
    bullets: [
      "Potência de 1500W para aquecimento rápido e eficiente",
      "3 níveis de potência para ajustar o conforto térmico",
      "Distribuição uniforme do calor no ambiente",
      "Sistema de segurança contra superaquecimento",
    ],
    voltage: ["110V", "220V"],
    weight: 2200,
    dims: [25, 20, 40],
  },
  {
    name: "Ventilador de Mesa Elgin Breeze Air",
    brand: "Elgin",
    categoryId: "climatizacao",
    price: 13990,
    card: [12, 1320],
    img: "ventilador",
    bullets: [
      "Potência de 140W para ventilação forte e eficiente",
      "Hélice de 7 pás e grade de 40cm para maior vazão de ar",
      "3 velocidades com oscilação horizontal automática",
      "Inclinação vertical regulável para melhor direcionamento do vento",
    ],
    voltage: ["220V"],
    weight: 2500,
    dims: [35, 30, 42],
  },
  {
    name: "Ventilador de Mesa Britânia Super Turbo BVT405",
    brand: "Britânia",
    categoryId: "climatizacao",
    price: 17990,
    card: [12, 1700],
    img: "ventilador",
    bullets: [
      "Potência de 150W para ventilação forte e maior desempenho",
      "Tecnologia Maxx Force com hélice de 6 pás e grade de 40cm",
      "3 velocidades com oscilação horizontal automática",
      "Uso 2 em 1: mesa ou parede, com grade removível",
    ],
    voltage: ["220V"],
    weight: 2600,
    dims: [35, 30, 42],
  },
  {
    name: "Ventilador de Mesa Mondial Super Power VSP-40-B",
    brand: "Mondial",
    categoryId: "climatizacao",
    price: 19990,
    card: [12, 1885],
    img: "ventilador",
    bullets: [
      "Potência de 140W para ventilação forte e eficiente",
      "Hélice de 6 pás e grade de 40cm para maior vazão de ar",
      "3 velocidades com modo turbo, conforto e silencioso",
      "Grade removível, alça de transporte e porta-fio embutido",
    ],
    voltage: ["220V"],
    weight: 2500,
    dims: [35, 30, 42],
  },
  {
    name: "Ventilador de Mesa Mondial Super Turbo VTX-40-8P",
    brand: "Mondial",
    categoryId: "climatizacao",
    price: 19990,
    card: [12, 1885],
    img: "ventilador",
    bullets: [
      "Potência de 140W para ventilação forte e eficiente",
      "Hélice de 8 pás e grade de 40cm para maior vazão de ar",
      "3 velocidades: turbo, conforto e silencioso",
      "Grade removível, alça de transporte e porta-fio embutido",
    ],
    voltage: ["220V"],
    weight: 2500,
    dims: [35, 30, 42],
  },
  {
    name: "Ventilador de Mesa Philco PVT402",
    brand: "Philco",
    categoryId: "climatizacao",
    price: 19990,
    card: [12, 1885],
    img: "ventilador",
    bullets: [
      "Potência de 160W com tecnologia Maxx Force para alta vazão de ar",
      "Função repelente e aromatizador com sensor de luz e 3 programações",
      "3 velocidades com oscilação horizontal e inclinação vertical regulável",
      "Grade removível, porta-fio e alça de transporte",
    ],
    voltage: ["220V"],
    weight: 2600,
    dims: [35, 30, 42],
  },
  {
    name: "Ventilador de Mesa Wap Flow Turbo",
    brand: "Wap",
    categoryId: "climatizacao",
    price: 19990,
    card: [12, 1890],
    img: "ventilador",
    bullets: [
      "Potência de 180W para ventilação forte e alto desempenho",
      "Hélice de 8 pás e grade de 50cm para máxima vazão de ar",
      "Modelo 2 em 1: mesa ou parede",
      "Grade removível e alça de transporte",
    ],
    voltage: ["110V"],
    weight: 3000,
    dims: [40, 35, 48],
  },
  {
    name: "Ventilador de Coluna Mondial Super Turbo VTX-40C-8P",
    brand: "Mondial",
    categoryId: "climatizacao",
    price: 23990,
    card: [12, 2260],
    img: "ventilador",
    bullets: [
      "Potência de 140W para ventilação forte e eficiente",
      "Hélice de 8 pás e grade de 40cm para maior vazão de ar",
      "3 velocidades: turbo, conforto e silencioso",
      "Altura regulável com oscilação horizontal e inclinação vertical",
    ],
    voltage: ["220V"],
    weight: 4800,
    dims: [45, 45, 130],
  },
  {
    name: "Ventilador de Parede Ventisol Premium 50cm",
    brand: "Ventisol",
    categoryId: "climatizacao",
    price: 21990,
    card: [12, 2075],
    img: "ventilador",
    bullets: [
      "Potência de 135W para ventilação forte e eficiente",
      "Hélice de 6 pás e grade de 50cm para maior vazão de ar",
      "Oscilação horizontal para melhor distribuição do vento",
      "Controle de velocidade por chave de parede",
      "Ideal para lojas, escritórios, igrejas e indústrias",
    ],
    voltage: ["220V"],
    weight: 3800,
    dims: [55, 20, 55],
    note: "Mais de R$ 300 em lojas físicas",
  },
  {
    name: "Ventilador de Parede Ventisol Premium 60cm",
    brand: "Ventisol",
    categoryId: "climatizacao",
    price: 23990,
    card: [12, 2260],
    img: "ventilador",
    bullets: [
      "Potência de até 200W para ventilação forte em grandes ambientes",
      "Grade de 60cm e hélice de 6 pás para maior vazão e alcance do ar",
      "Oscilação horizontal automática para melhor distribuição do vento",
      "Bivolt seletivo com chave de alteração de voltagem",
      "Ideal para lojas, escolas, igrejas, restaurantes e áreas comerciais",
    ],
    voltage: ["Bivolt seletivo"],
    weight: 4200,
    dims: [65, 22, 65],
    note: "Mais de R$ 300 em lojas físicas",
  },

  // ─── FERRAMENTAS ────────────────────────────────────────────────────────
  {
    name: "Esmerilhadeira Bosch GWS 700",
    brand: "Bosch",
    categoryId: "ferramentas",
    price: 22990,
    card: [12, 2170],
    img: "esmerilhadeira",
    bullets: [
      "Potência de 710W para cortes e desbastes com eficiência",
      "Design compacto e leve para maior conforto no uso",
      "Alta durabilidade para trabalhos frequentes",
      "Empunhadura ergonômica que oferece mais controle e segurança",
    ],
    voltage: ["220V"],
    weight: 2000,
    dims: [30, 10, 10],
  },
  {
    name: "Fechadura Digital Intelbras FR221V",
    brand: "Intelbras",
    categoryId: "ferramentas",
    price: 34990,
    card: [12, 3300],
    img: "fechadura",
    bullets: [
      "Abertura por biometria e senha digital para mais praticidade e segurança",
      "Cadastro de múltiplos usuários — ideal para residências, escritórios e comércios",
      "Travamento automático após o fechamento da porta",
      "Alerta de bateria fraca e sistema de segurança contra violação",
    ],
    weight: 1500,
    dims: [25, 10, 20],
  },
  {
    name: "Fechadura Digital Elsys Pop DS1100V",
    brand: "Elsys",
    categoryId: "ferramentas",
    price: 24990,
    card: [12, 2355],
    img: "fechadura",
    bullets: [
      "Abertura por senha ou tag de proximidade",
      "Instalação simples em portas de madeira",
      "Travamento automático para mais segurança",
      "Cadastro de múltiplos usuários",
    ],
    weight: 1400,
    dims: [25, 10, 20],
    note: "Entrega grátis em Uberlândia — mais de R$ 350 nas lojas físicas",
  },
  {
    name: "Parafusadeira Titanium 12V 7743",
    brand: "Titanium",
    categoryId: "ferramentas",
    price: 9990,
    card: [12, 950],
    img: "parafusadeira",
    bullets: [
      "Potência de 12V para uso doméstico e pequenos reparos",
      "Mandril de 3/8\" (10mm) para maior versatilidade",
      "Função reversível para parafusar e desparafusar com facilidade",
      "Acompanha 2 baterias e maleta",
    ],
    voltage: ["Bivolt (carregador 110V e 220V)"],
    weight: 1500,
    dims: [30, 25, 8],
    note: "Mais de R$ 150 em lojas físicas",
  },
  {
    name: "Parafusadeira Vonder 12V PFV012I",
    brand: "Vonder",
    categoryId: "ferramentas",
    price: 17990,
    card: [12, 1695],
    img: "parafusadeira",
    bullets: [
      "Potência de 12V com função impacto para maior versatilidade",
      "Torque de 30 N.m para perfurações mais fortes",
      "Duas velocidades variáveis para mais controle",
      "Mandril de 3/8\" (10mm) com aperto rápido",
    ],
    voltage: ["Bivolt (carregador 110V e 220V)"],
    weight: 1600,
    dims: [30, 25, 8],
    note: "Mais de R$ 250 em lojas físicas",
  },
  {
    name: "Kit de Ferramentas Tramontina 3 Peças 43408195",
    brand: "Tramontina",
    categoryId: "ferramentas",
    price: 4990,
    card: [12, 470],
    img: "ferramentas",
    bullets: ["Chave de fenda", "Chave phillips", "Martelo de unha 18mm"],
    weight: 400,
    dims: [20, 15, 4],
  },
  {
    name: "Kit de Ferramentas Tramontina 5 Peças 43408505",
    brand: "Tramontina",
    categoryId: "ferramentas",
    price: 4990,
    card: [12, 470],
    img: "ferramentas",
    bullets: [
      "Chave fixa 10x11mm e chave fixa 8x9mm",
      "Chave de fenda ponta chata 1/8 e 3/16",
      "Estilete retrátil 6\" com lâmina em aço especial",
    ],
    weight: 450,
    dims: [20, 15, 4],
  },
  {
    name: "Kit de Ferramentas Tramontina 5 Peças 43408502",
    brand: "Tramontina",
    categoryId: "ferramentas",
    price: 4990,
    card: [12, 470],
    img: "ferramentas",
    bullets: [
      "Chave de fenda ponta cruzada 3/16x4\" e ponta chata 3/16x3\" e 1/8x4\"",
      "Chave fixa 14x15mm Master cromada",
      "Chave fixa 10x11mm Master cromada",
    ],
    weight: 500,
    dims: [20, 15, 4],
  },
  {
    name: "Kit de Ferramentas Tramontina 5 Peças 43408142",
    brand: "Tramontina",
    categoryId: "ferramentas",
    price: 4990,
    card: [12, 470],
    img: "ferramentas",
    bullets: [
      "Alicate universal 7\" em aço especial com empunhadura injetada",
      "Estilete estreito 130mm e trena 2m",
      "Chave de fenda clipe Master Yellow ponta chata 1/8x3\" e ponta cruzada 3/16x3\"",
    ],
    weight: 450,
    dims: [20, 15, 4],
  },

  // ─── CASA E DECORAÇÃO ───────────────────────────────────────────────────
  {
    name: "Lixeira Tramontina Inox 5L",
    brand: "Tramontina",
    categoryId: "casa-decoracao",
    price: 4990,
    card: [12, 755],
    img: "lixeira",
    bullets: [
      "Capacidade de 5 litros, ideal para banheiros, cozinhas e escritórios",
      "Pedal de abertura para mais higiene e praticidade",
      "Fabricada em aço inox com acabamento polido e elegante",
      "Balde interno removível para facilitar a limpeza",
    ],
    weight: 800,
    dims: [25, 25, 30],
    note: "Mais de R$ 100 em lojas físicas",
  },
  {
    name: "Copo Stanley Beer Tumbler Happy Hour 384ml",
    brand: "Stanley",
    categoryId: "casa-decoracao",
    price: 9990,
    card: [12, 950],
    img: "copo",
    bullets: [
      "Mantém a bebida gelada por até 4 horas e com gelo por até 14 horas",
      "Fabricado em aço inox com isolamento térmico de alta qualidade",
      "Base emborrachada para mais estabilidade e proteção",
      "Edição limitada William Stanley Jr.",
    ],
    color: ["Branco", "Preto", "Metálico"],
    weight: 350,
    dims: [10, 10, 15],
    note: "Mais de R$ 150 em lojas físicas",
  },
  {
    name: "Copo Stanley Pilsner Glass Happy Hour 444ml",
    brand: "Stanley",
    categoryId: "casa-decoracao",
    price: 9990,
    card: [12, 950],
    img: "copo",
    bullets: [
      "Mantém a bebida gelada por até 4 horas e com gelo por até 14 horas",
      "Capacidade de 444ml, ideal para cervejas, drinks e bebidas geladas",
      "Fabricado em aço inox com isolamento térmico de alta performance",
      "Edição limitada William Stanley Jr.",
    ],
    color: ["Branco", "Preto", "Metálico"],
    weight: 380,
    dims: [10, 10, 17],
    note: "Mais de R$ 150 em lojas físicas",
  },
  {
    name: "Taça Térmica Cocktail Glass Stanley 414ml",
    brand: "Stanley",
    categoryId: "casa-decoracao",
    price: 19990,
    card: [12, 1883],
    img: "copo",
    bullets: [
      "Mantém a bebida gelada por até 4 horas e com gelo por até 16 horas",
      "Isolamento a vácuo com parede dupla em aço inox 18/8",
      "Capacidade de 414ml, ideal para drinks, vinhos e coquetéis",
      "Não sua por fora — base emborrachada e garantia vitalícia Stanley",
    ],
    color: ["Black Gloss", "Stainless"],
    weight: 400,
    dims: [11, 11, 18],
  },
  {
    name: "Kit Tramontina Churrasco 4 Peças",
    brand: "Tramontina",
    categoryId: "casa-decoracao",
    price: 14990,
    card: [12, 1415],
    img: "churrasco",
    bullets: [
      "Kit completo com tábua, faca, garfo e pegador para churrasco",
      "Tábua em madeira jatobá 40x30cm",
      "Utensílios em aço inox para mais durabilidade e precisão no corte",
      "Cabos anatômicos em polipropileno para maior conforto",
    ],
    weight: 1300,
    dims: [45, 30, 5],
    note: "Entrega grátis em Uberlândia",
  },
  {
    name: "Aparador Patrimar Vero com 2 Gavetas e Adega",
    brand: "Patrimar",
    categoryId: "casa-decoracao",
    price: 34990,
    card: [12, 3290],
    img: "movel",
    bullets: [
      "Adega integrada com capacidade para até 9 garrafas",
      "2 gavetas com corrediças telescópicas",
      "Tampo de 25mm e estrutura em MDP",
      "Pés palito em madeira maciça com sapatas protetoras",
    ],
    color: ["Preto"],
    weight: 35000,
    dims: [120, 40, 80],
    note: "Mais de R$ 500 em lojas físicas",
  },
  {
    name: "Extensão Múltipla Tramontina 5m",
    brand: "Tramontina",
    categoryId: "casa-decoracao",
    price: 4990,
    card: [12, 475],
    img: "extensao",
    bullets: [
      "Cabo de 5 metros para maior alcance e praticidade",
      "5 tomadas 2P+T para conectar vários equipamentos ao mesmo tempo",
      "Suporta até 10A e 250V com segurança",
    ],
    weight: 450,
    dims: [20, 15, 5],
  },

  // ─── ÁUDIO ──────────────────────────────────────────────────────────────
  {
    name: "Caixa de Som Torre Pulse Flamebox SP512",
    brand: "Pulse",
    categoryId: "eletronicos",
    price: 299990,
    card: [12, 28190],
    img: "caixasom",
    bullets: [
      "Potência de 5000W",
      "Show de luzes dinâmico que sincroniza com a batida",
      "IPX4 à prova de respingos, Bluetooth 5.0",
      "Entradas AUX, USB, SD, microfone e guitarra/violão",
      "Rodinhas para transporte e garantia de 3 anos",
    ],
    voltage: ["Bivolt"],
    weight: 25000,
    dims: [40, 40, 110],
    note: "Mais de R$ 5.000 nas lojas físicas",
  },

  // ─── ELETRODOMÉSTICOS ───────────────────────────────────────────────────
  {
    name: "Purificador Electrolux Efficient PE11X",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 59990,
    card: [12, 5650],
    img: "purificador",
    bullets: [
      "Água natural, fria ou gelada com um toque",
      "Filtro com carvão ativado e polipropileno",
      "Painel touch fácil de usar",
      "Aviso de troca do filtro",
    ],
    voltage: ["Bivolt"],
    color: ["Cinza"],
    weight: 6500,
    dims: [30, 30, 90],
  },
  {
    name: "Cooktop Consul 5 Bocas Preto Bivolt CDD75AE",
    brand: "Consul",
    categoryId: "eletrodomesticos",
    price: 74990,
    card: [12, 7062],
    img: "panela",
    bullets: [
      "5 bocas com queimador quadrichama",
      "Acendimento automático",
      "Mesa de vidro temperado",
      "Design moderno e fácil limpeza",
    ],
    voltage: ["Bivolt"],
    weight: 8500,
    dims: [70, 50, 10],
  },
  {
    name: "Micro-ondas Midea 20L MHP20S1",
    brand: "Midea",
    categoryId: "eletrodomesticos",
    price: 54990,
    card: [12, 5180],
    img: "microondas",
    bullets: [
      "20L de capacidade para o dia a dia",
      "Painel digital para mais praticidade",
      "Função descongelar",
      "Menu prático para preparar e aquecer alimentos",
    ],
    voltage: ["110V", "220V"],
    color: ["Prata espelhado"],
    weight: 11000,
    dims: [46, 36, 28],
  },
  {
    name: "Micro-ondas Electrolux MTO30",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 49990,
    card: [12, 4710],
    img: "microondas",
    bullets: [
      "Capacidade de 20 litros",
      "Painel digital fácil de usar",
      "Função tira odor",
      "Função descongelar",
    ],
    voltage: ["110V"],
    color: ["Branco"],
    weight: 11000,
    dims: [46, 36, 28],
  },
  {
    name: "Micro-ondas Electrolux Efficient 23L ME23B",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 49990,
    card: [12, 4710],
    img: "microondas",
    bullets: [
      "23L de capacidade e 1100W de potência",
      "Descongelamento assistido para mais praticidade",
      "Função manter aquecido e tira odor",
      "Funções derreter, desidratar e cozinhar",
    ],
    voltage: ["110V", "220V"],
    color: ["Branco"],
    weight: 13000,
    dims: [48, 38, 30],
  },
  {
    name: "Micro-ondas Electrolux Efficient 23L ME23P",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 54990,
    card: [12, 5180],
    img: "microondas",
    bullets: [
      "23L de capacidade e 1100W de potência",
      "Descongelamento assistido para mais praticidade",
      "Painel inteligente com funções práticas",
      "Trava do painel e modo economia de energia",
    ],
    voltage: ["110V"],
    color: ["Preto"],
    weight: 13000,
    dims: [48, 38, 30],
  },
  {
    name: "Micro-ondas Electrolux Efficient ME36B",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 61990,
    card: [12, 5840],
    img: "microondas",
    bullets: [
      "Capacidade de 36L e potência de 1600W",
      "Descongelamento assistido para mais praticidade",
      "Funções derreter, desidratar e fermentar",
      "Função tira odor e modo economia de energia",
    ],
    voltage: ["110V"],
    color: ["Branco"],
    weight: 16000,
    dims: [52, 42, 33],
  },
  {
    name: "Máquina de Lavar Electrolux 11kg LES11",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 159990,
    card: [12, 15070],
    img: "maquinalavar",
    bullets: [
      "Capacidade de 11kg, ideal para o uso diário da família",
      "Sistema Easy Clean que dilui o sabão e evita manchas nas roupas",
      "Ciclo rápido de 19 minutos",
      "Filtro pega fiapos e função reuso de água",
    ],
    voltage: ["110V"],
    weight: 36000,
    dims: [60, 60, 95],
  },
  {
    name: "Máquina de Lavar Electrolux LEE15 14,5kg",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 189990,
    card: [12, 17895],
    img: "maquinalavar",
    bullets: [
      "Capacidade de 14,5kg — lava até edredom queen size",
      "Tecnologia Jet&Clean que dilui o sabão e evita manchas",
      "Cesto em inox para mais durabilidade",
      "Ultra Filter que retém até 8x mais fiapos",
    ],
    voltage: ["110V", "220V"],
    weight: 40000,
    dims: [62, 62, 100],
  },
  {
    name: "Lava-Louças Midea 8 Serviços MDWTF08W1",
    brand: "Midea",
    categoryId: "eletrodomesticos",
    price: 189990,
    card: [12, 17895],
    img: "maquinalavar",
    bullets: [
      "Capacidade de 8 serviços, ideal para casas pequenas e médias",
      "Painel full touch fácil e intuitivo de usar",
      "Função higieniza frutas e embalagens",
      "Secagem extra e programas intenso e pré-lavagem",
    ],
    voltage: ["220V"],
    weight: 40000,
    dims: [60, 60, 85],
    note: "Mais de R$ 2.500 em lojas físicas",
  },

  // ─── ELETROPORTÁTEIS ────────────────────────────────────────────────────
  {
    name: "Air Fryer Kitchen Art KFR01 5,7L",
    brand: "Kitchen Art",
    categoryId: "eletrodomesticos",
    price: 29990,
    card: [12, 2820],
    img: "airfryer",
    bullets: [
      "Potência de 1500W para preparo rápido e eficiente",
      "Capacidade de 5,7L total com cesto de 4,3L",
      "Temperatura ajustável de até 200°C",
      "Timer de 60 minutos e design premium em inox",
    ],
    voltage: ["110V"],
    weight: 5300,
    dims: [35, 33, 34],
    note: "Mais de R$ 500 nas lojas físicas",
  },
  {
    name: "Air Fryer Britânia BFR50 Redstone 5,5L",
    brand: "Britânia",
    categoryId: "eletrodomesticos",
    price: 24990,
    card: [12, 2354],
    img: "airfryer",
    bullets: [
      "Capacidade de 5,5L, ideal para preparar refeições para toda a família",
      "Potência de 1500W para preparos mais rápidos e crocantes",
      "Fritura com pouco ou nenhum óleo",
      "Cesto com revestimento antiaderente para facilitar a limpeza",
    ],
    voltage: ["110V"],
    weight: 5200,
    dims: [35, 33, 34],
  },
  {
    name: "Lavadora de Alta Pressão Karcher Compacta",
    brand: "Karcher",
    categoryId: "eletrodomesticos",
    price: 34990,
    card: [12, 3296],
    img: "aspirador",
    bullets: [
      "Potência de 1400W para limpeza eficiente",
      "Pressão de até 1500 PSI para sujeiras pesadas",
      "Aplicador de detergente e mangueira de 3 metros",
      "Design compacto e ergonômico",
    ],
    voltage: ["110V"],
    weight: 4200,
    dims: [30, 25, 40],
  },
  {
    name: "Batedeira Planetária Mondial Premium BP-01P-W",
    brand: "Mondial",
    categoryId: "eletrodomesticos",
    price: 29990,
    card: [12, 2825],
    img: "batedeira",
    bullets: [
      "Potência de 700W para preparar massas com mais facilidade",
      "Movimento planetário que garante misturas mais homogêneas",
      "12 velocidades e 2 tigelas de 4,5L",
      "Acompanha 3 batedores e tampa antirrespingos",
    ],
    voltage: ["220V"],
    weight: 4500,
    dims: [36, 24, 34],
  },
  {
    name: "Mixer Processador Philips Walita Pro Mix RI2530",
    brand: "Philips Walita",
    categoryId: "eletrodomesticos",
    price: 9990,
    card: [12, 942],
    img: "liquidificador",
    bullets: [
      "Potência de 250W para preparar receitas com mais agilidade",
      "Tecnologia Pro Mix para misturas mais homogêneas",
      "Função 2 em 1: mixer e processador de alimentos",
      "Lâminas em aço inox e design fácil de limpar",
    ],
    voltage: ["220V"],
    color: ["Branco"],
    weight: 1000,
    dims: [15, 10, 40],
  },
  {
    name: "Mixer Britânia 2 em 1 350W BMX360",
    brand: "Britânia",
    categoryId: "eletrodomesticos",
    price: 13990,
    card: [12, 1320],
    img: "liquidificador",
    bullets: [
      "350W de potência para misturar e triturar",
      "2 em 1: mixer e processador de alimentos",
      "Lâminas Pro Maxx em aço inox",
      "Copo de 1,05L e processador de 600ml",
    ],
    voltage: ["220V"],
    weight: 1100,
    dims: [15, 10, 40],
  },
  {
    name: "Liquidificador Britânia Diamante 800",
    brand: "Britânia",
    categoryId: "eletrodomesticos",
    price: 11990,
    card: [12, 1130],
    img: "liquidificador",
    bullets: [
      "Potência de 1050W para preparos mais rápidos e eficientes",
      "Jarra com capacidade de 2,6L, ideal para toda a família",
      "4 velocidades e funções pulsar, ice e autolimpeza",
      "4 lâminas em aço inox e filtro para sucos",
    ],
    voltage: ["220V"],
    color: ["Preto"],
    weight: 3100,
    dims: [24, 22, 42],
  },
  {
    name: "Liquidificador Britânia BLQ1100",
    brand: "Britânia",
    categoryId: "eletrodomesticos",
    price: 11990,
    card: [12, 1130],
    img: "liquidificador",
    bullets: [
      "Potência de 1100W para triturar e misturar com mais eficiência",
      "Jarra com capacidade total de 2,7L e 1,5L útil",
      "4 velocidades e funções pulsar, ice e autolimpeza",
      "4 lâminas em aço inox, ideal para sucos, vitaminas e molhos",
    ],
    voltage: ["110V"],
    color: ["Preto"],
    weight: 3100,
    dims: [24, 22, 42],
  },
  {
    name: "Ferro a Vapor Mondial FVN-01-O",
    brand: "Mondial",
    categoryId: "eletrodomesticos",
    price: 10990,
    card: [12, 1030],
    img: "ferro",
    bullets: [
      "Potência de 1200W para aquecimento rápido e maior eficiência",
      "Base cerâmica diamante que proporciona deslizamento mais suave",
      "Função passa a seco e a vapor",
      "Sistema autolimpeza e cabo giratório 360°",
    ],
    voltage: ["220V"],
    weight: 1200,
    dims: [30, 14, 16],
    note: "Entrega grátis em Uberlândia",
  },
  {
    name: "Ferro Electrolux a Vapor e a Seco SIE60 Azul",
    brand: "Electrolux",
    categoryId: "eletrodomesticos",
    price: 10990,
    card: [12, 1036],
    img: "ferro",
    bullets: [
      "Potência de 1500W para aquecimento rápido e maior eficiência",
      "Base antiaderente que proporciona deslizamento suave",
      "Vapor vertical para desamassar roupas diretamente no cabide",
      "Sistema antigotas e autolimpeza",
    ],
    voltage: ["220V"],
    color: ["Azul"],
    weight: 1200,
    dims: [30, 14, 16],
    note: "Entrega grátis em Uberlândia",
  },
  {
    name: "Ferro a Vapor Arno Essentialgliss FMQ",
    brand: "Arno",
    categoryId: "eletrodomesticos",
    price: 10990,
    card: [12, 1036],
    img: "ferro",
    bullets: [
      "Potência de 1200W para aquecimento rápido e maior eficiência",
      "Base antiaderente que desliza facilmente sobre os tecidos",
      "Função vapor e a seco, com vapor contínuo e spray",
      "Seletor de temperatura para diferentes tipos de tecidos",
    ],
    voltage: ["110V"],
    weight: 1150,
    dims: [30, 14, 16],
    note: "Entrega grátis em Uberlândia",
  },
  {
    name: "Sanduicheira Cadence Toast & Grill SAN260",
    brand: "Cadence",
    categoryId: "eletrodomesticos",
    price: 7990,
    card: [12, 752],
    img: "sanduicheira",
    bullets: [
      "Potência de 750W para preparo rápido e eficiente",
      "Chapas antiaderentes que evitam que os alimentos grudem",
      "Design compacto com alça isotérmica que não aquece",
      "Trava de fechamento e LED indicador de funcionamento",
    ],
    voltage: ["110V"],
    weight: 1600,
    dims: [28, 24, 12],
  },
  {
    name: "Sanduicheira e Grill Philco PGR21PI Maxx Clean",
    brand: "Philco",
    categoryId: "eletrodomesticos",
    price: 16990,
    card: [12, 1600],
    img: "sanduicheira",
    bullets: [
      "Potência de 1000W para preparo rápido de sanduíches e grelhados",
      "Revestimento Maxx Clean até 4x mais resistente",
      "Abertura superior ajustável até 180°",
      "Bandeja coletora de gordura e acabamento em inox",
    ],
    voltage: ["220V"],
    weight: 1700,
    dims: [28, 24, 12],
    note: "Mais de R$ 250 nas lojas físicas",
  },

  // ─── BELEZA ─────────────────────────────────────────────────────────────
  {
    name: "Chapa Taiff Style Azul",
    brand: "Taiff",
    categoryId: "beleza",
    price: 19990,
    card: [12, 1880],
    img: "beleza",
    bullets: [
      "Temperatura de até 210°C para alisamento eficiente",
      "Tecnologia PTC que mantém o calor estável",
      "Aquecimento rápido para mais praticidade",
      "Cabo de 1,8m para maior liberdade de movimentos",
    ],
    voltage: ["Bivolt"],
    color: ["Azul"],
    weight: 500,
    dims: [30, 8, 6],
  },
  {
    name: "Secador Britânia BSC2050",
    brand: "Britânia",
    categoryId: "beleza",
    price: 19990,
    card: [12, 1871],
    img: "beleza",
    bullets: [
      "Potência de 2000W com motor AC profissional",
      "3 temperaturas e 2 velocidades para todos os tipos de cabelo",
      "Jato de ar frio para melhor fixação do penteado",
      "Bocal concentrador para escovas e finalizações",
    ],
    voltage: ["110V", "220V"],
    weight: 700,
    dims: [25, 12, 10],
  },
  {
    name: "Secador de Cabelo Britânia SP3100N",
    brand: "Britânia",
    categoryId: "beleza",
    price: 11990,
    card: [12, 1130],
    img: "beleza",
    bullets: [
      "Potência de 2000W para secagem rápida e eficiente",
      "3 temperaturas e 2 velocidades para todos os tipos de cabelo",
      "Jato de ar frio para fixar o penteado",
      "Design leve e ergonômico para maior conforto no uso",
    ],
    voltage: ["110V"],
    weight: 650,
    dims: [25, 12, 10],
  },

  // ─── INFORMÁTICA E GAMES ────────────────────────────────────────────────
  {
    name: "Cadeira Gamer XT Racer Speed Series",
    brand: "XT Racer",
    categoryId: "informatica",
    price: 79990,
    card: [12, 7535],
    img: "cadeira",
    bullets: [
      "Design gamer ergonômico para maior conforto durante longas horas de uso",
      "Encosto reclinável para ajustar a posição ideal",
      "Apoio de braços e altura reguláveis",
      "Revestimento resistente com acabamento premium",
    ],
    weight: 20000,
    dims: [70, 70, 130],
  },
  {
    name: 'Monitor LG UHD 4K 32" 32UL750-W',
    brand: "LG",
    categoryId: "informatica",
    price: 249990,
    card: [12, 23545],
    img: "monitor",
    bullets: [
      'Tela UHD 4K de 32" com HDR600 para imagens mais realistas',
      "Painel VA com alta qualidade de cores e contraste apurado",
      "USB-C com transmissão de vídeo, dados e carregamento de até 60W",
      "AMD FreeSync e tempo de resposta de 4ms",
    ],
    weight: 6000,
    dims: [75, 20, 50],
    note: "Mais de R$ 3.500 em lojas físicas",
  },
  {
    name: 'Monitor Samsung Odyssey G40 25"',
    brand: "Samsung",
    categoryId: "informatica",
    price: 139990,
    card: [12, 13184],
    img: "monitor",
    bullets: [
      "Taxa de atualização de 240Hz para máxima fluidez",
      "Tempo de resposta de apenas 1ms",
      "NVIDIA G-Sync e AMD FreeSync Premium",
      "Ideal para jogos competitivos e e-sports",
    ],
    weight: 4500,
    dims: [58, 18, 42],
  },
  {
    name: "Mouse Gamer Asus TUF Gaming M3",
    brand: "Asus",
    categoryId: "informatica",
    price: 11990,
    card: [12, 1130],
    img: "mouse",
    bullets: [
      "Sensor gamer de alta precisão com até 7000 DPI",
      "Design leve e ergonômico para longas partidas",
      "Iluminação RGB compatível com Aura Sync",
      "7 botões programáveis",
    ],
    weight: 150,
    dims: [12, 8, 4],
  },
  {
    name: "Mouse Lenovo ThinkPad MoRFn60",
    brand: "Lenovo",
    categoryId: "informatica",
    price: 11990,
    card: [12, 1130],
    img: "mouse",
    bullets: [
      "Conexão sem fio via USB-C e Bluetooth com troca rápida entre dispositivos",
      "Emparelhamento com até 8 dispositivos",
      "Sensor óptico com ajuste de até 2400 DPI",
      "Rolagem em 4 direções e bateria de longa duração",
    ],
    weight: 130,
    dims: [12, 8, 4],
  },
  {
    name: "Kit Mouse Lenovo ThinkPad + Mochila Targus Intellect",
    brand: "Lenovo / Targus",
    categoryId: "informatica",
    price: 19990,
    card: [12, 1885],
    img: "mochila",
    bullets: [
      "Kit completo para trabalho, estudo e viagens",
      "Mouse sem fio com alta precisão e conforto",
      'Mochila com compartimento para notebook de até 15,6"',
      "Material resistente à água",
    ],
    weight: 1050,
    dims: [45, 30, 15],
  },
  {
    name: 'Mochila Targus Intellect Essentials TSB966 15,6"',
    brand: "Targus",
    categoryId: "informatica",
    price: 10990,
    card: [12, 1035],
    img: "mochila",
    bullets: [
      'Compartimento acolchoado para notebooks de até 15,6"',
      "Material em poliéster resistente à água",
      "Painel traseiro em air mesh e alças acolchoadas",
      "Bolsos e compartimentos para organizar notebook e acessórios",
    ],
    weight: 900,
    dims: [45, 30, 15],
  },
  {
    name: "Kit Gamer Dazz Arsenal",
    brand: "Dazz",
    categoryId: "informatica",
    price: 18990,
    card: [12, 1785],
    img: "teclado",
    bullets: [
      "Kit completo com teclado, mouse, headset e mousepad",
      "Iluminação RGB para um setup mais estiloso",
      "Teclas macias e confortáveis para longas partidas",
      "Compatibilidade plug and play",
    ],
    weight: 2000,
    dims: [45, 30, 8],
  },
  {
    name: "Fone Gamer Dazz Immersion",
    brand: "Dazz",
    categoryId: "informatica",
    price: 11990,
    card: [12, 1130],
    img: "fone",
    bullets: [
      "Áudio surround 7.1 para maior imersão",
      "Graves potentes e som mais envolvente",
      "Microfone integrado",
      "Conexão USB para instalação rápida",
    ],
    weight: 400,
    dims: [22, 20, 11],
  },
  {
    name: "Fone Gamer OEX Shield HS409",
    brand: "OEX",
    categoryId: "informatica",
    price: 14990,
    card: [12, 1410],
    img: "fone",
    bullets: [
      "Áudio surround 7.1 para maior imersão nos jogos",
      "Haste ajustável para mais conforto",
      "Controle de LED e microfone no próprio headset",
      "Conexão USB com instalação simples",
    ],
    weight: 420,
    dims: [22, 20, 11],
    note: "Mais de R$ 300 em lojas físicas",
  },

  // ─── SMART TVS ──────────────────────────────────────────────────────────
  {
    name: "Soundbar Samsung HW-B450F",
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 99990,
    card: [12, 9417],
    img: "caixasom",
    bullets: [
      "Potência de 300W para um som mais envolvente",
      "Subwoofer sem fio para graves mais impactantes",
      "Dolby Audio e DTS Virtual:X com efeito cinema",
      "Modo Bass Boost para reforço de graves",
    ],
    weight: 4200,
    dims: [90, 12, 10],
    note: "Mais de R$ 1.300 em lojas físicas",
  },
  {
    name: 'Smart TV Toshiba 32" HD 32V35L TB016M',
    brand: "Toshiba",
    categoryId: "smart-tvs",
    price: 89990,
    card: [12, 8476],
    img: "tv",
    bullets: [
      "Tela DLED HD com imagens nítidas e cores vibrantes",
      "Sistema VIDAA com acesso aos principais apps de streaming",
      "Dolby Audio para um som mais envolvente",
      "Espelhamento de tela, Wi-Fi integrado, 2 HDMI e 2 USB",
    ],
    weight: 4300,
    dims: [75, 15, 50],
  },
  {
    name: 'Smart TV Samsung 32" H5000F',
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 99990,
    card: [12, 9417],
    img: "tv",
    bullets: [
      "Imagem HD com cores mais vibrantes",
      "HDR10+ para mais detalhes nas cenas",
      "Sistema Tizen rápido e intuitivo",
      "Wi-Fi e espelhamento de tela integrados",
    ],
    weight: 4300,
    dims: [75, 15, 50],
  },
  {
    name: 'Smart TV LG Full HD AI 43" 43LR6700PSA',
    brand: "LG",
    categoryId: "smart-tvs",
    price: 169990,
    card: [12, 16010],
    img: "tv",
    bullets: [
      "Tela Full HD com HDR10 Pro para imagens mais nítidas",
      "Processador α5 AI Gen6 que otimiza imagem e som",
      "webOS 23 com acesso aos principais apps de streaming",
      "Painel e otimizador de jogos para gamers",
    ],
    voltage: ["Bivolt"],
    weight: 8000,
    dims: [98, 16, 62],
  },
  {
    name: 'Smart TV Samsung 43" QLED Full HD Q5F',
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 179900,
    card: [12, 16951],
    img: "tv",
    bullets: [
      "Tela QLED Full HD com cores mais vivas e detalhadas",
      "Processador para melhorar a qualidade da imagem",
      "Sistema Tizen com acesso aos principais apps",
      "Design slim e moderno",
    ],
    weight: 8000,
    dims: [98, 16, 62],
  },
  {
    name: 'Smart TV LG UHD AI 4K 50" 50UA8550PSA',
    brand: "LG",
    categoryId: "smart-tvs",
    price: 209990,
    card: [12, 19776],
    img: "tv",
    bullets: [
      "Processador α7 AI 4K geração 8 para imagem e som otimizados",
      "HDR10 Pro e 4K Upscaling para mais nitidez e cores vibrantes",
      "webOS 25 com acesso aos principais apps",
      "AI ThinQ com comandos de voz",
    ],
    weight: 11500,
    dims: [113, 17, 71],
  },
  {
    name: 'Smart TV Samsung 50" Crystal UHD U8100F',
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 219990,
    card: [12, 20720],
    img: "tv",
    bullets: [
      "Imagem 4K com cores mais vivas e detalhes incríveis",
      "Processador Crystal 4K para melhor qualidade de imagem",
      "Gaming Hub para jogar sem console",
      "Alexa integrada e comando de voz",
    ],
    weight: 11500,
    dims: [113, 17, 71],
  },
  {
    name: 'Smart TV Samsung 55" Crystal UHD 4K U8600F',
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 259990,
    card: [12, 24485],
    img: "tv",
    bullets: [
      "Processador Crystal 4K com upscaling para imagens mais nítidas",
      "Tela 4K com HDR para mais contraste e detalhes",
      "Samsung Gaming Hub para jogar na nuvem sem console",
      "Sistema One UI Tizen, controle solar e SmartThings",
    ],
    weight: 14500,
    dims: [124, 18, 78],
    note: "Mais de R$ 3.000 em lojas físicas",
  },
  {
    name: 'Smart TV Samsung 75" Crystal UHD 4K U8600F',
    brand: "Samsung",
    categoryId: "smart-tvs",
    price: 479990,
    card: [12, 45200],
    img: "tv",
    bullets: [
      "Processador Crystal 4K com upscaling para imagens mais nítidas",
      "Tela 4K com HDR para mais contraste e detalhes",
      "Samsung Gaming Hub para jogar na nuvem sem console",
      "Sistema One UI Tizen, controle solar e SmartThings",
    ],
    weight: 28000,
    dims: [168, 20, 100],
    note: "Mais de R$ 5.500 em lojas físicas",
  },

  // ─── SMARTPHONES ────────────────────────────────────────────────────────
  {
    name: "Smartphone Motorola Signature 5G",
    brand: "Motorola",
    categoryId: "celulares",
    price: 419990,
    card: [12, 39550],
    img: "smartphone",
    bullets: [
      "512GB de armazenamento para fotos, vídeos, apps e arquivos",
      "Até 24GB de RAM com RAM Boost para máxima performance",
      "Tela Extreme AMOLED 1.5K de 165Hz para imagens ultra fluidas",
      "Câmeras Sony LYTIA de 50MP com zoom de até 100x",
      "Processador de alto desempenho com 5G",
    ],
    color: ["Verde Oliva"],
    weight: 220,
    dims: [17, 8, 1],
    note: "Mais de R$ 7.500 em lojas físicas",
  },
];

const CATEGORY_PREFIX: Record<string, string> = {
  "smart-tvs": "TV",
  celulares: "CEL",
  eletrodomesticos: "ELD",
  climatizacao: "CLM",
  eletronicos: "ELT",
  informatica: "INF",
  ferramentas: "FER",
  "casa-decoracao": "CSA",
  beleza: "BLZ",
};

function buildLoja(d: LojaDraft, index: number): Product {
  const prefix = CATEGORY_PREFIX[d.categoryId] ?? "DG";
  const specifications: Specification[] = d.bullets.map((value, i) => ({
    label: `Destaque ${i + 1}`,
    value,
  }));
  if (d.color?.length) {
    specifications.push({ label: "Cor", value: d.color.join(", ") });
  }

  // Só vira variante SELECIONÁVEL quando há de fato mais de uma opção — uma
  // "escolha" com um único valor força um clique extra sem sentido (e some
  // com o botão "Adicionar ao carrinho" na vitrine à toa). Voltagem única
  // entra como especificação normal.
  const variants =
    d.voltage && d.voltage.length > 1
      ? [{ name: "Voltagem", options: d.voltage }]
      : undefined;
  if (d.voltage?.length === 1) {
    specifications.push({ label: "Voltagem", value: d.voltage[0] });
  }

  const slug = `${slugify(d.name)}-${index}`;

  return {
    id: `loja-${index}`,
    name: d.name,
    slug,
    description: d.bullets.slice(0, 2).join(". ") + ".",
    price: d.price,
    categoryId: d.categoryId,
    brand: d.brand,
    sku: `DG-${prefix}-${String(index + 1).padStart(3, "0")}`,
    stock: 5,
    images: resolveImages(slug, d.name, d.img),
    variants,
    specifications,
    shipping: {
      weight: d.weight,
      dimensions: { length: d.dims[0], width: d.dims[1], height: d.dims[2] },
      origin: "Minas Gerais",
    },
    isFeatured: false,
    isBestSeller: false,
    isOffer: false,
    isExclusive: Boolean(d.exclusive),
    tags: d.name
      .toLowerCase()
      .split(/\s+/)
      .filter((w) => w.length > 3)
      .slice(0, 8),
    dataSource: "loja-verified",
    cardInstallment: { count: d.card[0], value: d.card[1] },
    sellerNote: d.note,
  };
}

function slugify(name: string): string {
  return name
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

export const lojaProducts: Product[] = drafts.map(buildLoja);
export { LOJA_VERIFIED_AT };
